---
title: "Files"
description: |
  What are tasks, and how do they work in Sykdomspulsen Core?
date: 2021-05-26
author:
  - first_name: "Richard Aubrey"
    last_name: "White"
    url: https://www.fhi.no
    affiliation: Folkehelseinstituttet
    affiliation_url: https://www.fhi.no
    orcid_id: 0000-0002-6747-1726
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
options(knitr.kable.NA = '')
library(sykdomspulsen)
library(data.table)
library(magrittr)
library(sc)
```

## Introduction

A task is the basic operational unit of Sykdomspulsen Core. It is based on [plnr](https://folkehelseinstituttet.github.io/plnr/).

In short, you can think of a Sykdomspulsen Core task as multiple [plnr plans](https://folkehelseinstituttet.github.io/plnr/) plus [Sykdomspulsen Core db schemas](analytics_db_schemas_introduction.html).

## Definitions

```{r, echo=FALSE}
options(width = 150)
readLines("https://raw.githubusercontent.com/folkehelseinstituttet/scskeleton/main/R/00_env_and_namespace.r")
```

## Changelog {.appendix}

2021-05-26: Draft created.

